-- 解决postgresql操作无权限的问题，以下语句需使用postgres账号执行，都是以schema为public为示例
-- 1. 数据库级全权限
GRANT ALL PRIVILEGES ON DATABASE 数据库名 TO 账号;
-- 2. public模式：允许访问+创建对象（含建表）
GRANT USAGE,CREATE ON SCHEMA PUBLIC TO 账号;
-- 3. 未来新建对象默认全权限
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL PRIVILEGES ON TABLES TO 账号;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL PRIVILEGES ON SEQUENCES TO 账号;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL PRIVILEGES ON FUNCTIONS TO 账号;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL PRIVILEGES ON TYPES TO 账号;
-- 4. 现有对象全权限（表、序列、函数）
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO 账号;
GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA public TO 账号;
GRANT ALL PRIVILEGES ON ALL FUNCTIONS IN SCHEMA public TO 账号;